backbonedemo/Controllers/BetterController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Dts.Mvc.Controllers;
using Dts.Infrastructure.Logging;

namespace BackboneDemo.Controllers
{
    public class BetterController : BaseController
    {
        public BetterController(ILogger logger)
            : base(logger)
        {
        }

        public ActionResult Index()
        {            
            return View();
        }
    }
}

backbonedemo/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Dts.Mvc.Controllers;
using Dts.Infrastructure.Logging;

namespace BackboneDemo.Controllers
{
    public class HomeController : BaseController
    {
        public HomeController(ILogger logger)
            : base(logger)
        {
        }

        public ActionResult Index()
        {            
            return View();
        }

        public ActionResult CameraTest()
        {
            ViewBag.ImageName = TempData["ImageName"];
            return View();
        }

        [HttpPost]
        public ActionResult CameraTest(IEnumerable<HttpPostedFileBase> pics)
        {
            var pic = pics.FirstOrDefault();
            if (pic != null)
            {
                pic.SaveAs(Server.MapPath("~/public/uploads/" + pic.FileName));
            }
            
            TempData["ImageName"] = pic.FileName;

            return RedirectToAction("CameraTest");
        }
    }
}

backbonedemo/Controllers/MapExtentController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Dts.Mvc.Controllers;
using Dts.Infrastructure.Logging;

namespace BackboneDemo.Controllers
{
    public class MapExtentController : BaseController
    {
        public MapExtentController(ILogger logger)
            : base(logger)
        {
        }

        public ActionResult Index()
        {            
            return View();
        }       
    }
}

backbonedemo/Controllers/MousePositionController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Dts.Mvc.Controllers;
using Dts.Infrastructure.Logging;

namespace BackboneDemo.Controllers
{
    public class MousePositionController : BaseController
    {
        public MousePositionController(ILogger logger)
            : base(logger)
        {
        }

        public ActionResult Index()
        {            
            return View();
        }
    }
}

backbonedemo/Controllers/SearchAppController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Dts.Mvc.Controllers;
using Dts.Infrastructure.Logging;

namespace BackboneDemo.Controllers
{
    public class SearchAppController : BaseController
    {
        public SearchAppController(ILogger logger)
            : base(logger)
        {
        }

        public ActionResult Index()
        {            
            return View();
        }
    }
}

backbonedemo/Views/Home/CameraTest.cshtml
@{
    ViewBag.Title = "CameraTest";
}

<h2>Camera Test</h2>

@using (Html.BeginForm("CameraTest", "Home", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
	<input type="file" accept="image/*" capture="camera" id="pics" name="pics" />
    <input type="submit" />	 
}


@if (ViewBag.ImageName != null)
{
    <img src="@Url.Content("~/public/uploads/" + (string)ViewBag.ImageName)" />    
}

backbonedemo/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Index";
}

<style type="text/css">
    body {width:100%; font-size: 120%;}
    div {width:600px;margin: 0 auto 0 auto;}
    a {display:block; margin-top: 15px; color: blue;}
</style>

<div>

    <h1>Backbone.js demos</h1>

    <a href="http://help.arcgis.com/en/webapi/javascript/arcgis/demos/map/map_currentextent.html">Esri Show Map Extent Sample</a>

    @Html.ActionLink("Backbone Show Map Extent", "Index", "MapExtent")

   @* <a href="http://help.arcgis.com/en/webapi/javascript/arcgis/demos/map/map_xycoords.html">Esri Show Mouse Coordinates Sample</a>

    @Html.ActionLink("Backbone Show Mouse Coordinates", "Index", "MousePosition")*@

    @Html.ActionLink("Awesomer!", "Index", "Better")

    @Html.ActionLink("A more realistic scenario", "Index", "SearchApp")
    
    <a href="@Url.Content("~/public/javascript/tests/tests.htm")">Tests!</a>

</div>